#s1: the file need to be updated
scp $1 ssd16:~/code/disAlexNet
scp $1 ssd17:~/code/disAlexNet
scp $1 ssd18:~/code/disAlexNet
scp $1 ssd19:~/code/disAlexNet
scp $1 ssd20:~/code/disAlexNet
scp $1 ssd21:~/code/disAlexNet
scp $1 ssd22:~/code/disAlexNet
scp $1 ssd23:~/code/disAlexNet
scp $1 ssd24:~/code/disAlexNet
scp $1 ssd25:~/code/disAlexNet
scp $1 ssd26:~/code/disAlexNet
scp $1 ssd27:~/code/disAlexNet
scp $1 ssd28:~/code/disAlexNet
scp $1 ssd29:~/code/disAlexNet
scp $1 ssd30:~/code/disAlexNet
scp $1 ssd31:~/code/disAlexNet
scp $1 ssd32:~/code/disAlexNet
scp $1 ssd33:~/code/disAlexNet
scp $1 ssd34:~/code/disAlexNet
scp $1 ssd35:~/code/disAlexNet
scp $1 ssd36:~/code/disAlexNet
scp $1 ssd37:~/code/disAlexNet
scp $1 ssd38:~/code/disAlexNet
scp $1 ssd39:~/code/disAlexNet
scp $1 ssd40:~/code/disAlexNet
scp $1 ssd41:~/code/disAlexNet
